### ISSUE TITLE
[IMPROVE IDEA] docked when other sensor is closed

### ISSUE THREAD

**Issue by DAVIZINH0** [galletn/iaqualink#27] opened 2024-07-07 17:33 UTC
Hello.
I have a maybe stupid idea but i think its interesting to tell you.
my robot is  zodiac XA 5095 IQ and works fine in home assistant now with the last version (july 2024).
But the robot only report 2 states:
Cleaning: when the robot is cleaning in the pool
Idle: when the robot is not cleaning

The problem is the idle state, because the robot can be in the pool (in the water ) or in the dock (outside the water).
It will be interesting to know when the robot is in the water or outside the water. because I can make a automation that clean the pool at some hour of the day only when the robot is in the water. If the robot its outside the water I dont want to start cleaning.

The problem with this idea is the robot not report when it is in the water or ouside the water.
And I have a idea to solve this:
- A contact sensor!!!

I use a contact sensor (aqara zigbee door sensor) atached to the cable and when this sensor is "closed" I am sure that the robot its ouside the water. And when the sensor is "open" i am sure that the robot its IN the water.

And now comes my stupid idea!!!
It will be interesting if the sensor is "closed" the robot apears as "DOCKED" in his state.
I dont know how dificult is this. Maybe its hard! and stupid. but i want to share this idea with you :-)

**Comment by galletn** [comment] 2024-07-26 19:48
the issue is that you want to access data from another sensor from within this code, what basically is not a good idea as naming wise everyone would need to use the exact same model and name for that sensor. I think it would be smarter to create an automation with node red for this. Did you try node red before?

**Comment by DAVIZINH0** [comment] 2024-07-27 14:09
Hello

Actually i use a automation in home assistant, and check the sensor before star cleaning.

You are right in my case i use aqara sensor and it will be dificult to make a standard.

Thanks for your reply, as i said, Maybe this is a stupid idea. Jejeje

**Comment by galletn** [comment] 2024-08-01 19:49
I'll close the issue to keep the list clean of okay 😄

**Closed** 2024-08-01 19:49 UTC
Labels: enhancement
